services:
  frontend:
    image: node:24-alpine
    ports:
      - 5173:5173
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "npm install && npm run dev -- --host"
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:5173